[Path]
# RWTH
#trainDataPath = /home/lj/lj/program/python/DataSets/phoenix-2014.v3/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train
#validDataPath = /home/lj/lj/program/python/DataSets/phoenix-2014.v3/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/dev
#testDataPath = /home/lj/lj/program/python/DataSets/phoenix-2014.v3/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/test
#trainLabelPath = data/RWTH/train.corpus.csv
#validLabelPath = data/RWTH/dev.corpus.csv
#testLabelPath = data/RWTH/test.corpus.csv
# RWTH-T
#trainDataPath = /home/lj/lj/program/python/DataSets/PHOENIX-2014-T-release-v3/PHOENIX-2014-T/features/fullFrame-210x260px/train
#validDataPath = /home/lj/lj/program/python/DataSets/PHOENIX-2014-T-release-v3/PHOENIX-2014-T/features/fullFrame-210x260px/dev
#testDataPath = /home/lj/lj/program/python/DataSets/PHOENIX-2014-T-release-v3/PHOENIX-2014-T/features/fullFrame-210x260px/test
#trainLabelPath = data/RWTH-T/PHOENIX-2014-T.train.corpus.csv
#validLabelPath = data/RWTH-T/PHOENIX-2014-T.dev.corpus.csv
#testLabelPath = data/RWTH-T/PHOENIX-2014-T.test.corpus.csv
# CSL-Daily
#trainDataPath = /home/lj/lj/program/python/DataSets/CSL-Daily/sentence/frames_512x512
#validDataPath = /home/lj/lj/program/python/DataSets/CSL-Daily/sentence/frames_512x512
#testDataPath = /home/lj/lj/program/python/DataSets/CSL-Daily/sentence/frames_512x512
#trainLabelPath = /home/lj/lj/program/python/SLR20240523/data/CSL-Daily/train.txt
#validLabelPath = /home/lj/lj/program/python/SLR20240523/data/CSL-Daily/dev.txt
#testLabelPath = /home/lj/lj/program/python/SLR20240523/data/CSL-Daily/test.txt
# CE-CSL
trainDataPath = D:\Graduation_Thesis\TEST\CE-CSL\train
validDataPath = D:\Graduation_Thesis\TEST\CE-CSL\train
# (testDataPath may be the same location or a separate folder of test videos)
testDataPath = D:\Graduation_Thesis\TEST\CE-CSL\train
trainLabelPath = D:\Graduation_Thesis\TEST\CE-CSL\train.csv
validLabelPath = D:\Graduation_Thesis\TEST\CE-CSL\train.csv
testLabelPath = D:\Graduation_Thesis\TEST\CE-CSL\train.csv

bestModuleSavePath = module/bestMoudleLightTFNet.pth
currentModuleSavePath = module/currentMoudleLightTFNet.pth

[Params]
device = 1
hiddenSize = 1024
lr = 0.0001
batchSize = 2
numWorkers = 0
pinmMemory = 1
moduleChoice = LightTFNet
dataSetName = CE-CSL
