[Path]
trainDataPath = D:\Graduation_Thesis\TEST\CE-CSL\train
validDataPath = D:\Graduation_Thesis\TEST\CE-CSL\dev
# (testDataPath may be the same location or a separate folder of test videos)
testDataPath = D:\Graduation_Thesis\TEST\CE-CSL\test
trainLabelPath = D:\Graduation_Thesis\TEST\CE-CSL\train.csv
validLabelPath = D:\Graduation_Thesis\TEST\CE-CSL\dev.csv
testLabelPath = D:\Graduation_Thesis\TEST\CE-CSL\test.csv

bestModuleSavePath = module/bestMoudleLightTFNet.pth
currentModuleSavePath = module/currentMoudleLightTFNet.pth

[Params]
device = 1
hiddenSize = 1024
lr = 0.0001
batchSize = 2
numWorkers = 0
pinmMemory = 1
moduleChoice = LightTFNet
dataSetName = CE-CSL
